# fly.toml app configuration file generated for runmates-back-icy-shadow-4369 on 2025-04-06T13:29:51-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'runmates-back-icy-shadow-4369'
primary_region = 'qro'

[build]
  dockerfile = "Dockerfile"
  context = "."

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
