name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Clean pnpm cache (if needed)
      - run: pnpm store prune

      # Install dependencies with pnpm
      - run: pnpm install --frozen-lockfile

      # Install Playwright dependencies
      - run: pnpm playwright install --with-deps

      # Set SHAs for Nx caching (optional)
      - uses: nrwl/nx-set-shas@v4

      # Run Nx affected commands for linting, testing, and building
      - run: pnpm nx affected -t lint test build